apiVersion: v1
kind: Service
metadata:
  name: kanban-backend
  namespace: default
spec:
  selector:
    app: kanban-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  # ClusterIP = פנימי בלבד, לא חשוף לאינטרנט
  type: ClusterIP
